---

- name: config apache22 server
  hosts: aws
  tasks:


  - name: install apache and php packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{php_package}}"
      state: latest
      update_cache: yes


