---
- name: config apache22 server
  hosts: aws
  tasks:

  - name: update repo index
    package:
      update_cache: yes


  - name: install apache2 server
    apt:
      name: apache2
      state: latest


  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
