---
- name: remove apache22 server
  hosts: aws
  tasks:

  - name: update repo index
    package:
      update_cache: yes


  - name: remove apache2 server
    apt:
      name: apache2
      state: absent


  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
