---

- name: config apache22 server
  hosts: aws
  tasks:


  - name: install apache and php packages
    tags: apache and php
    package:
      name: 
        - "{{ apache_package }}"
        - "{{php_package}}"
      state: latest
      update_cache: yes

- hosts: aws
  tasks:

  - name: install mariadb pachages(ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install samba package
    package:
      name: samba
      state: latest
