---
- name: Update web servers
  hosts: aws
  remote_user: root

  tasks:
  - name: Ensure apache is at the latest version
    package:
      name: apache2
      state: latest

- name: Update db servers
  hosts: databases
  remote_user: root

  tasks:
  - name: Ensure postgresql is at the latest version
    apt:
      name: postgresql postgresql-contrib postgresql-client
      state: latest
  - name: Ensure that postgresql is started
    service:
      name: postgresql postgresql-contrib postgresql-client
      state: started